# Generated by Django 4.2 on 2026-04-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enrollment_completed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='lesson_id',
            new_name='chapter_id',
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('enrollment', 'chapter_id')},
        ),
        migrations.AddField(
            model_name='progress',
            name='quiz_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='progress',
            name='last_accessed',
        ),
    ]
