http:
  routers:
    # Frontend remains static as it's the entry point
    frontend:
      rule: "PathPrefix(`/`)"
      service: "frontend-srv"
      priority: 1

  services:
    # Frontend remains static or via Docker labels
    frontend-srv:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
