# Generated by Django 4.2 on 2026-04-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
