# Generated by Django 4.2 on 2026-04-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quiz_chapter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions_per_attempt',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='selected_questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
