# Generated by Django 4.2.7 on 2026-04-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.IntegerField(default=1),
        ),
    ]
