# Generated by Django 4.2.7 on 2026-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_course_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='domain',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
