# Generated by Django 4.2.7 on 2026-04-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_chapter_delete_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pdf_file',
        ),
    ]
