# Generated by Django 4.2.7 on 2026-04-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_remove_course_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='domain',
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='course_app.domain')),
            ],
            options={
                'unique_together': {('domain', 'name')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course_app.specialization'),
        ),
        migrations.CreateModel(
            name='InstructorSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.IntegerField()),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.specialization')),
            ],
            options={
                'unique_together': {('instructor_id', 'specialization')},
            },
        ),
    ]
