import os
import django
from django.core.files.base import ContentFile

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'course_project.settings')
django.setup()

from course_app.models import Course, Chapter

print("Wiping existing chapters...")
Chapter.objects.all().delete()

courses = Course.objects.all()
if not courses:
    print("No courses found. Creating some fallback courses...")
    c1 = Course.objects.create(title="Introduction to Machine Learning", description="Learn ML basics.", domain="Computer Science", instructor_id=2)
    c2 = Course.objects.create(title="Advanced Calculus", description="Math 301.", domain="Mathematics", instructor_id=2)
    courses = [c1, c2]

print("Populating chapters for each course...")
for course in courses:
    print(f"Creating chapters for course: {course.title} (ID: {course.id})...")
    
    # Create 3 chapters per course
    for i in range(1, 4):
        chapter = Chapter.objects.create(
            course=course,
            title=f"Module {i}: Fundamental Principles",
            description=f"This is an autogenerated chapter covering the essential concepts for Module {i}.",
            order=i
        )
        
        # Attach a mock PDF file
        pdf_content = b"%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>\nendobj\n4 0 obj\n<< /Length 53 >>\nstream\nBT\n/F1 24 Tf\n100 700 Td\n(Mock PDF Content) Tj\nET\nendstream\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF"
        chapter.pdf_file.save(f"module_{i}_course_{course.id}.pdf", ContentFile(pdf_content), save=True)

print("Course chapters successfully populated!")
